name: Build CI

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    tags: [ v* ]
  pull_request:
  merge_group:

jobs:
  build:
    runs-on: macos-latest
    env:
      CCACHE_COMPILERCHECK: '%compiler% -dumpmachine; %compiler% -dumpversion'
      CCACHE_NOHASHDIR: 'true'
      CCACHE_HARDLINK: 'true'
      CCACHE_BASEDIR: ${{ github.workspace }}
      GITHUB_TOKEN: "${{ secrets.GH_TOKEN }}"

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Fetch all
      run: |
        git submodule foreach --recursive "git fetch --tags"

    - name: Cache Gradle
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Cache Maven local repo
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-m2-${{ hashFiles('**/build.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-m2-

    - name: Cache ccache
      uses: actions/cache@v4
      with:
        path: ~/.ccache
        key: ${{ runner.os }}-ccache-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-ccache-

    - name: Write signing key if needed
      if: github.ref == 'refs/heads/master' && github.event_name != 'pull_request'
      run: |
        if [ ! -z "${{ secrets.KEY_STORE }}" ]; then
          echo androidStorePassword='${{ secrets.KEY_STORE_PASSWORD }}' >> gradle.properties
          echo androidKeyAlias='${{ secrets.ALIAS }}' >> gradle.properties
          echo androidKeyPassword='${{ secrets.KEY_PASSWORD }}' >> gradle.properties
          echo androidStoreFile='key.jks' >> gradle.properties
          echo ${{ secrets.KEY_STORE }} | base64 --decode > key.jks
        fi

    - name: Write random data to machikado&mazoku
      run: |
        dd if=/dev/random of=./manager/src/main/assets/machizako.arm bs=96 count=1
        dd if=/dev/random of=./manager/src/main/assets/machizako.arm64 bs=96 count=1
        dd if=/dev/random of=./manager/src/main/assets/machizako.x64 bs=96 count=1
        dd if=/dev/random of=./manager/src/main/assets/machizako.x86 bs=96 count=1
        dd if=/dev/random of=./manager/src/main/assets/machizako.riscv64 bs=96 count=1
        dd if=/dev/random of=./manager/src/main/assets/mazako bs=96 count=1

    - name: Checkout libxposed/api
      uses: actions/checkout@main
      with:
        repository: libxposed/api
        path: libxposed/api
        ref: 54582730315ba4a3d7cfaf9baf9d23c419e07006

    - name: Checkout libxposed/service
      uses: actions/checkout@main
      with:
        repository: libxposed/service
        path: libxposed/service

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'adopt'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Setup ninja
      uses: seanmiddleditch/gha-setup-ninja@master
      with:
        version: 1.12.0

    - name: Remove Android's cmake
      run: rm -rf $ANDROID_HOME/cmake

    - name: Build local dependencies
      run: |
        echo "--- Building API dependency ---"
        cd libxposed/api
        ./gradlew :api:publishApiPublicationToMavenLocal --no-daemon
        echo "--- Building Service Interface dependency ---"
        cd ../service
        ./gradlew :interface:publishInterfacePublicationToMavenLocal --no-daemon

    - name: Set short commit id
      run: echo "commit=$(echo ${{ github.sha }} | cut -c-7)" >> $GITHUB_ENV

    - name: Build with Gradle
      run: |
        echo 'org.gradle.parallel=true' >> gradle.properties
        echo 'org.gradle.jvmargs=-Xmx3g' >> gradle.properties
        echo 'android.native.buildOutput=verbose' >> gradle.properties
        ./gradlew buildAll

    - name: Upload Debug artifact
      uses: actions/upload-artifact@v4
      with:
        name: lspatch-debug
        path: out/debug/*

    - name: Upload Release artifact
      uses: actions/upload-artifact@v4
      with:
        name: lspatch-release
        path: out/release/*

    - name: Upload to KV
      if: success()
      run: |
        curl -X POST -H "x-token: ${{ secrets.BOT_TOKEN }}" -H "x-filename: $(basename $(ls out/release/LSPatch-v*-release.apk))" --data-binary @$(ls out/release/LSPatch-v*-release.apk) https://${{ secrets.BOT_WORKER}}/uploadPatch
        sleep 5
        curl -X POST -H "x-token: ${{ secrets.BOT_TOKEN }}" -H "x-filename: $(basename $(ls out/debug/LSPatch-v*-release-log.apk))" --data-binary @$(ls out/debug/LSPatch-v*-release-log.apk) https://${{ secrets.BOT_WORKER}}/uploadPatchDebug

    - name: Upload to Telegram
      if: success()
      run: |
        versionCode=$(basename $(ls out/release/LSPatch-v*-release.apk) | cut -d'-' -f5)
        message_file="$GITHUB_WORKSPACE/message.txt"
        echo "New version pushed: $versionCode" > "$message_file"
        echo -n "新版本已推送：$versionCode" >> "$message_file"
        message=$(cat "$message_file")
        curl -s -X POST -H "Content-Type: application/json" -d '{"chat_id": "${{ secrets.CHAT_ID }}", "message_thread_id": "${{ secrets.MESSAGE_THREAD_ID }}", "text": "'"$message"'", "reply_markup": {"inline_keyboard": [[{"text": "Download / 下载", "url": "https://t.me/${{ secrets.BOT_NAME }}?start=dl_patch"}]]}}' "https://api.telegram.org/bot${{ secrets.BOT_TOKEN }}/sendMessage" >> /dev/null
